#!/bin/bash
#SBATCH -p RM        
#SBATCH -t 1:00:00
#SBATCH --cpus-per-task=1 
#SBATCH --array=1-1001%100  #include +1 since the last job fails  
#SBATCH --mem=20G
#SBATCH -o slurm/out.%A_%a

source ~/main/miniforge3/etc/profile.d/conda.sh
conda activate LSST

echo "Running task ${SLURM_ARRAY_TASK_ID}"

cd /hildafs/home/pladuca/main/lsst-sim-package/LSST-SimCatVal/LSST-SimCatVal

## Hyperparams
diff_path="/hildafs/home/pladuca/main/lsst-sim-package/LSST-SimCatVal/LSST-SimCatVal/diffsky_new"
im_size=900
skycat="/hildafs/home/pladuca/main/skyCatalog.yaml"
Dp1_sample="/hildafs/home/pladuca/main/lsst-sim-package/LSST-SimCatVal/LSST-SimCatVal/ECDFS_1000_psf_e12.pkl"
save_path="/hildafs/home/pladuca/main/lsst-sim-package/LSST-SimCatVal/LSST-SimCatVal/outputs_vdiffnew"

diff_path=${1:-$diff_path}
im_size=${2:-$im_size}
skycat=${3:-$skycat}
Dp1_sample=${4:-$Dp1_sample}
save_path=${5:-$save_path}

python main.py ${SLURM_ARRAY_TASK_ID} ${skycat} ${Dp1_sample} ${im_size} ${save_path} ${diff_path}

echo 'done!'
